## CA1 Machine Learning

### Banking Dataset taked from UC Irvine Machine Learning Repository
####  https://archive.ics.uci.edu/dataset/2/adult
#### creators Barry Becker & Ronny Kohavi
#### Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset.

#### Associated Task = Classification
#### Dataset Characteristics = Multivariate
#### Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the following conditions: ((AAGE>16) && (AGI>100) && (AFNLWGT>1)&& (HRSWK>0))
#### Prediction task is to determine whether a person's income is over $50,000 a year.

## License
#### This dataset is licensed under a Creative Commons Attribution 4.0 International (CC BY 4.0) license.

#### This allows for the sharing and adaptation of the datasets for any purpose, provided that the appropriate credit is given.

## Data Preparation

## Import Libraries

In [10]:
import pandas as pd
import seaborn as sns
%matplotlib inline  
import matplotlib.pyplot as plt
import numpy as np

####  No column headers exist on the data file, import as header=None
#### As per site, Variable names should be
#### age, workclass, fnlwgt, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loss, hours-per-week, native-country, income_target

### Read in data file

In [11]:
df = pd.read_csv("adult.data", header=None) # no header, to be allocated later

In [12]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [13]:
#### As per site, Variable names should be
#### age, workclass, fnlwgt, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loss, hours-per-week, native-country, income_target

### Add a dictionary to place columns into the headers

In [15]:
Column_Header =  {
                    df.columns[0]:  'age',
                    df.columns[1]:  'workclass',
                    df.columns[2]:  'fnlwgt',
                    df.columns[3]:  'education',
                    df.columns[4]:  'education-num',
                    df.columns[5]:  'marital-status',
                    df.columns[6]:  'occupation',
                    df.columns[7]:  'relationship',
                    df.columns[8]:  'race',
                    df.columns[9]:  'sex',
                    df.columns[10]:  'capital-gain',
                    df.columns[11]: 'capital-loss',
                    df.columns[12]: 'hours-per-week',
                    df.columns[13]: 'native-country',
                    df.columns[14]: 'income',
                    
                  }


df.rename(columns = Column_Header, inplace = True) # adding a dictionary to place columns into the headers

In [16]:
df.head(5)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

### Create duplicate dataframe with required columns only

In [19]:
# create duplicate dataframe with required columns only
df_income = df[
                ["age", 
                 "education", 
                  "education-num", 
                  "marital-status",
                  "occupation", 
                  "relationship",
                  "capital-gain", 
                  "capital-loss", 
                  "hours-per-week", 
                  "income"] 
                ].copy()

In [20]:
df_income.head(5)

,age,education,education-num,marital-status,occupation,relationship,capital-gain,capital-loss,hours-per-week,income
0,39,Bachelors,13,Never-married,Adm-clerical,Not-in-family,2174,0,40,<=50K
1,50,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,0,0,13,<=50K
2,38,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,0,0,40,<=50K
3,53,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,0,0,40,<=50K
4,28,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,0,0,40,<=50K

In [21]:
df_income.tail(5)

,age,education,education-num,marital-status,occupation,relationship,capital-gain,capital-loss,hours-per-week,income
32556,27,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,0,0,38,<=50K
32557,40,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,0,0,40,>50K
32558,58,HS-grad,9,Widowed,Adm-clerical,Unmarried,0,0,40,<=50K
32559,22,HS-grad,9,Never-married,Adm-clerical,Own-child,0,0,20,<=50K
32560,52,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,15024,0,40,>50K

In [22]:
df_income.shape

(32561, 10)

In [26]:
df_income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   education       32561 non-null  object
 2   education-num   32561 non-null  int64
 3   marital-status  32561 non-null  object
 4   occupation      32561 non-null  object
 5   relationship    32561 non-null  object
 6   capital-gain    32561 non-null  int64
 7   capital-loss    32561 non-null  int64
 8   hours-per-week  32561 non-null  int64
 9   income          32561 non-null  object
dtypes: int64(5), object(5)
memory usage: 2.5+ MB

In [27]:
df_income.isnull().sum()

age               0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
capital-gain      0
capital-loss      0
hours-per-week    0
income            0
dtype: int64

#### No missing values with selected columns

In [28]:
df_income.dtypes

age                int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
income            object
dtype: object

In [30]:
df_income["income"].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64